version: '3.6'

services:
  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: perchandcobsdb
      MONGO_INITDB_ROOT_PASSWORD: perchandcobsdb2021
    container_name: mongodb
    ports:
      - "27017:27017"
  app:
    image: route-poisson-api:latest
    ports:
      - 8081:8080
#      - 27017:27017
#    expose:
#      - "27017"
