version: '3.6'

services:
  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    container_name: mongodb
    ports:
      - "27017:27017"
  app:
    image: route-poisson-api:0.0.1-SNAPSHOT
    ports:
      - 8080:8080
      - 27017:27017
    expose:
      - "27017"
